update base to 22.04
Signed-off-by: laminar <tpiperatgod@gmail.com>

diff --git a/python-builder/buildpacks/python-function-framework/bin/build b/python-builder/buildpacks/python-function-framework/bin/build
--- a/python-builder/buildpacks/python-function-framework/bin/build
+++ b/python-builder/buildpacks/python-function-framework/bin/build
@@ -2,17 +2,26 @@
 
 set -eo pipefail
 
+if [ -z "$FUNCTION_SOURCE" ]; then
+  echo "ERROR: missing FUNCTION_SOURCE environment variable"
+  exit 1
+else 
+  if [ ! -f "$FUNCTION_SOURCE" ]; then
+    echo "ERROR: $FUNCTION_SOURCE file not found"
+    exit 1
+  fi
+fi
+
+if [ -z "$FUNCTION_TARGET" ]; then
+  echo "ERROR: missing FUNCTION_TARGET environment variable"
+  exit 1
+fi
+
 # Create the python layer directory if it doesn't exist
 PYTHON_LAYER="$CNB_LAYERS_DIR/python"
 mkdir -p $PYTHON_LAYER
 
-# fetch function name from env
-if [ -z "$FUNCTION_NAME" ]; then
-  echo "ERROR: missing FUNCTION_NAME env var"
-  exit 1
-fi
-
-# Install the Python dependencies into
+# Install the Python dependencies
 python3 -m venv "$PYTHON_LAYER"/venv
 source "$PYTHON_LAYER"/venv/bin/activate
 pip3 install -r requirements.txt
@@ -20,54 +29,16 @@ pip3 install -r requirements.txt
 # Set layer metadata
 echo -e "[types]\nlaunch = true" > "$PYTHON_LAYER.toml"
 
-# Copy the function_context.py file to the app directory
-echo -e "from dapr.ext.grpc import App, InvokeMethodRequest, InvokeMethodResponse
-from dapr.clients import DaprClient
-
-
-class FunctionContext():
-    def __init__(self, name, port) -> None:
-        self.name = name
-        self.port = port
-        self.dapr_client = DaprClient
-        self.app = App()
-        self.user_function = None
-        self.request = None
-
-    def load_user_function(self, user_function):
-        self.user_function = user_function
-
-    def invoke_user_function(self, request):
-        self.request = request
-        if self.user_function:
-            output_data = self.user_function(self)
-            return output_data
-        else:
-            raise ValueError(\"User function is not loaded.\")
-
-    def run(self):
-        @self.app.method(name=self.name)
-        def function_method(request: InvokeMethodRequest) -> InvokeMethodResponse:
-            output_data = self.invoke_user_function(request)
-            return InvokeMethodResponse(output_data.encode(), \"text/plain; charset=UTF-8\")
-
-        self.app.run(self.port)" > function_framework.py
-
 # Create the user function with the function name
 mkdir -p app
 touch app/__init__.py
-mv app.py app/app.py
-# sed -i 's/from function_framework import FunctionContext/from .function_framework import FunctionContext/g' app/app.py
-echo -e "\n\nif __name__ == '__main__':
-    fc = FunctionContext(\"$FUNCTION_NAME\", 50051)
-    fc.load_user_function(user_function)
-    fc.run()" >> app/app.py
+mv "$FUNCTION_SOURCE" "app/$FUNCTION_TARGET.py"
 
 # Write the launch.toml file
 cat > "$CNB_LAYERS_DIR/launch.toml" << EOL
 # our web process
 [[processes]]
 type = "web"
-command = "source $PYTHON_LAYER/venv/bin/activate && PYTHONPATH=$PWD python app/app.py"
+command = "source $PYTHON_LAYER/venv/bin/activate && PYTHONPATH=$PWD ff --source app/$FUNCTION_SOURCE --target $FUNCTION_TARGET"
 default = true
 EOL
diff --git a/python-builder/buildpacks/python-function-framework/bin/detect b/python-builder/buildpacks/python-function-framework/bin/detect
--- a/python-builder/buildpacks/python-function-framework/bin/detect
+++ b/python-builder/buildpacks/python-function-framework/bin/detect
@@ -12,4 +12,9 @@ if [ ! -f /workspace/requirements.txt ]; then
   exit 1
 fi
 
+if grep -q "ofn-functions-framework" /workspace/requirements.txt; then
+  echo "ERROR: requirements.txt dosen't contain ofn-functions-framework"
+  exit 1
+fi
+
 exit 0
